### ISSUE TITLE
cannot use lib.rs functions

### ISSUE THREAD

**Issue by jacobesplin** [Mahdrentys/wasm-cookies-rs#10]
Hello, 
I am having an issue porting in all the function from the lib.rs, however, I am able to reach the cookies.rs
use wasm_cookies;
let cookie_value = wasm_cookies::all();

cannot find function `all` in crate `wasm_cookies`

**Comment by echochamber** [comment]
You need to make sure you are building for the wasm32 target, otherwise [those symbols aren't included](https://docs.rs/wasm-cookies/latest/src/wasm_cookies/lib.rs.html#44-48)

```toml
# Cargo.toml
[[bin]]
name = "mybin"
path = "src/main.rs"
target = "wasm32-unknown-unknown"

# or

[[lib]]
name = "mylib"
target = "wasm32-unknown-unknown"
```
